In [1]:
import numpy as np

In [2]:
ar1=np.array(6)

In [3]:
ar2=np.array([[1,2,3],[4,5,6]])

In [4]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
ar3=np.array([1,2,3])

In [6]:
ar3

array([1, 2, 3])

In [7]:
zero_array=np.zeros((1,2))

In [8]:
zero_array

array([[0., 0.]])

In [9]:
ar4=np.arange(5,6,9)

In [10]:
ar4

array([5])

In [11]:
ar5=np.transpose(ar3)

In [12]:
ar5

array([1, 2, 3])

In [13]:
ar6=np.ravel(ar5)

In [14]:
ar6

array([1, 2, 3])

In [15]:
a1=np.array([1,2])
a2=np.array([3,4])